services:
     jarves.twig.extension.navigation:
         class: Jarves\Twig\NavigationExtension
         arguments: ["@jarves.navigation"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.nodeIsActive:
         class: Jarves\Twig\NodeIsActiveExtension
         arguments: ["@jarves.page_stack"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.nodeUrl:
         class: Jarves\Twig\NodeUrlExtension
         arguments: ["@jarves.page_stack"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.loadAsset:
         class: Jarves\Twig\LoadAssetExtension
         arguments: ["@jarves.page_stack"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.file:
         class: Jarves\Twig\FileExtension
         arguments: ["@jarves", "@jarves.filesystem.web"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.breadcrumb:
         class: Jarves\Twig\BreadcrumbExtension
         arguments: ["@jarves", "@jarves.page_stack", "@jarves.cache.cacher"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.content:
         class: Jarves\Twig\ContentExtension
         tags:
            - { name: twig.extension }

     jarves.twig.extension.tray:
         class: Jarves\Twig\TrayExtension
         arguments: ["@service_container"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.plugin:
         class: Jarves\Twig\PluginExtension
         arguments: ["@service_container"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.unsearchable:
         class: Jarves\Twig\UnsearchableExtension
         tags:
            - { name: twig.extension }

     jarves.twig.extension.headertag:
         class: Jarves\Twig\AdditionalHeaderTagExtension
         arguments: ["@jarves.page_stack"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.translate:
         class: Jarves\Twig\TranslateExtension
         arguments: ["@jarves.translator"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.renderContents:
         class: Jarves\Twig\RenderContentsExtension
         arguments: ["@service_container"]
         tags:
            - { name: twig.extension }

     jarves.twig.extension.markdowner:
         class: Jarves\Twig\MarkdownerExtension
         arguments: ["@jarves.markdowner"]
         tags:
            - { name: twig.extension }